services:
  - type: web
    name: calculator-app
    runtime: docker
    repo: https://github.com/Gregory-123-coder/dotnet-demo
    plan: free
    region: oregon
    branch: main
    dockerfilePath: Dockerfile
    autoDeploy: true
